name: Shopify API Changelog Notifier

on:
  schedule:
    - cron: '0 6 * * *'  # Runs daily at 6 AM UTC
  workflow_dispatch:      # Allows manual trigger

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install feedparser
        run: pip install feedparser

      - name: Fetch and process RSS
        run: |
          python scripts/fetch_changelog.py
